#! /bin/bash

# downloads 1080p movies, not present on 'surelyDownloaded' which match the minImdb criteria and was released on any year in the list grep --line-buffered -E '2016|2015|2014|2013|...'

WANTED_YEARS="2016|2015|2014|2013|2012|2011|2010|2009|2008|2007|2006|2005|2004|2003|2002|2001|2000"

for i in {1..3}; do curl -s "https://yts.ag/browse-movies/0/1080p/all/0/latest?page=$i" | lua -e 'minImdb=5 a=io.read("*a") a:gsub([[<a href="(https://yts.ag/movie/[^"]+)"%s+class="browse%-movie%-link">]], function (movie_link) a:gsub([[<a href="]]..(movie_link:gsub("%-", "%%-"))..[["%s+class="browse%-movie%-link">.-<h4 class="rating">([0-9%.]*)]], function (imdb) if (tonumber(imdb) >= tonumber(minImdb)) then print(movie_link) end end) end)'; done | grep -E "$WANTED_YEARS" | while read l; do u=`grep -Fxv -f /raid0/tmp/yts/surelyDownloaded <(echo "$l")`; if [ "$u" == "$l" ]; then echo "--> downloading 1080p $u..."; /root/bin/downloadYTS1080p "$u" && echo "$u" >>/raid0/tmp/yts/surelyDownloaded; else echo "--> skipping $l for it is on the list"; fi; done

# downloads 720p movies, not present on 'surelyDownloaded' (and also not downloaded in 1080p) which match the minImdb criteria and was released on any year in the list grep --line-buffered -E '2016|2015|2014|2013|...'

for i in {1..3}; do curl -s "https://yts.ag/browse-movies/0/720p/all/0/latest?page=$i" | lua -e 'minImdb=5 a=io.read("*a") a:gsub([[<a href="(https://yts.ag/movie/[^"]+)"%s+class="browse%-movie%-link">]], function (movie_link) a:gsub([[<a href="]]..(movie_link:gsub("%-", "%%-"))..[["%s+class="browse%-movie%-link">.-<h4 class="rating">([0-9%.]*)]], function (imdb) if (tonumber(imdb) >= tonumber(minImdb)) then print(movie_link) end end) end)'; done | grep -E "$WANTED_YEARS" | while read l; do u=`grep -Fxv -f /raid0/tmp/yts/surelyDownloaded <(echo "$l")`; if [ "$u" == "$l" ]; then echo "--> attempting to download $u in 1080p for the last time..." && /root/bin/downloadYTS1080p "$u" && echo "$u" >>/raid0/tmp/yts/surelyDownloaded || (echo "--> downloading 720p $u..." && /root/bin/downloadYTS720p "$u" && echo "$u" >>/raid0/tmp/yts/surelyDownloaded); else echo "--> skipping $l for it is on the list"; fi; done

