#!/bin/bash

((i=0))
while true; do
        cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp)
        cpuTemp1=$(($cpuTemp0/1000))
        cpuTemp2=$(($cpuTemp0/100))
        cpuTempM=$(($cpuTemp2 % $cpuTemp1))
         
        gpuTemp0=$(/opt/vc/bin/vcgencmd measure_temp)
        gpuTemp0=${gpuTemp0//\'/°}
        gpuTemp0=${gpuTemp0//temp=/}
         
        echo -en "`date +%H:%M:%S` - CPU: ${cpuTemp1}.${cpuTempM}°C; GPU: ${gpuTemp0}   "

        sleep 300
        ((i++))
        if ((i%4==0)); then
                echo
        else
                echo -en "\t"
        fi
done
